language: python

sudo: required
dist: focal

addons:
  apt:
    packages:
    - git
    - build-essential
    - automake
    - libtool
    - python-dev
    - gettext
    - swig

python:
  - "2.7"

git:
  depth: 10

before_install:
    - pip install --upgrade pip autopep8
    - pip3 install --upgrade pip autopep8

script:
- echo compiling xtraEvent plugin
- python -m compileall .
- echo done!

after_success:
- ./build.sh
